import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
               <div className="app-wrapper"> 
 <Navbar/>
         <div className="main-content"> 

        {children}
         <ToastContainer 
        position="bottom-right" 
        autoClose={1000} 
        hideProgressBar 
        closeOnClick 
        pauseOnHover={false} 
        draggable={false} 
        theme="colored"
      />
        </div>
        <Footer/>
        </div>
        </AuthProvider>

      </body>
    </html>
  );
}
